# Generated by Django 3.1.4 on 2021-01-27 08:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swahili', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 8, 33, 47, 598644, tzinfo=utc), verbose_name='date published'),
        ),
    ]
